### ISSUE TITLE
ImportError: DLL load failed while importing pyarmor_runtime

### ISSUE THREAD

**Issue by aVitomin** [UnidentifiedCitizen/Tarkov_KD_Dropper#1]
```
PS C:\aboba> python slave.py
Traceback (most recent call last):
  File "C:\aboba\slave.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\aboba\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ImportError: DLL load failed while importing pyarmor_runtime: Не найден указанный модуль.
```

**Comment by aVitomin** [comment]
Del
